export const labels = [
    'Case ID',
    'Verified',
    'Date Modified',
    'Last Modified By',
    'Entry date',
    'Reported date',
    'Case status',
    'Country',
    'Admin3',
    'Location',
    'Age',
    'Gender',
    'Outcome',
    'Hospitalization date',
    'Symptoms onset date',
    'Source URL',
];

export const createData = (
    caseId: string,
    verified: boolean,
    dateModified: string,
    lastModifiedBy: string,
    country: string,
    admin1?: string,
    admin2?: string,
    admin3?: string,
    location?: string,
    dateEntry?: string,
    dateReported?: string,
    age?: string,
    gender?: string,
    outcome?: string,
    dateHospitalization?: string,
    dateOnset?: string,
    source?: string,
    caseStatus?: string,
    comment?: string,
) => {
    return {
        age: age || '',
        caseId: caseId || '',
        caseStatus: caseStatus || '',
        comment: comment || '',
        country: country || '',
        dateEntry: dateEntry || '',
        dateHospitalization: dateHospitalization || '',
        dateModified: dateModified || '',
        dateOnset: dateOnset || '',
        dateReported: dateReported || '',
        admin2: admin2 || '',
        gender: gender || '',
        lastModifiedBy: lastModifiedBy || '',
        location: location || '',
        outcome: outcome || '',
        admin3: admin3 || '',
        admin1: admin1 || '',
        source: source || '',
        verified: verified || false,
    };
};
