export const labels = [
    'Bundle ID',
    'Case Count',
    'Verification Status',
    'Cases In Bundle',
    'Date Modified',
    'Last Modified By',
    'Case Status',
    'Entry date',
    'Reported date',
    'Country',
    'State',
    'Region',
    'District',
    'Location',
    'Age',
    'Gender',
    'Outcome',
    'Hospitalization date',
    'Symptoms onset date',
    'Source URL',
];

export const createData = (
    caseBundleId: string,
    caseCount: number,
    verificationStatus: boolean[],
    casesInBundle: number[],
    dateModified: string,
    lastModifiedBy: string,
    caseBundleStatus: string,
    country: string,
    admin1?: string,
    admin2?: string,
    admin3?: string,
    location?: string,
    dateEntry?: string,
    dateReported?: string,
    age?: string,
    gender?: string,
    outcome?: string,
    dateHospitalization?: string,
    dateOnset?: string,
    source?: string,
) => {
    return {
        caseBundleId: caseBundleId || '',
        caseCount: caseCount,
        verificationStatus: verificationStatus || [],
        casesInBundle: casesInBundle || [],
        dateModified: dateModified || '',
        lastModifiedBy: lastModifiedBy || '',
        caseBundleStatus: caseBundleStatus || '',
        dateEntry: dateEntry || '',
        dateReported: dateReported || '',
        country: country || '',
        admin1: admin1 || '',
        admin2: admin2 || '',
        admin3: admin3 || '',
        location: location || '',
        age: age || '',
        gender: gender || '',
        outcome: outcome || '',
        dateHospitalization: dateHospitalization || '',
        dateOnset: dateOnset || '',
        source: source || '',
    };
};
