name: Integration Tests CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/integration-tests.yml"
      - "dev/docker-compose.yml"
      - "verification/curator-service/**"
      - "data-serving/data-service/**"
      - "data-serving/samples/**"
  pull_request:
    paths:
      - ".github/workflows/integration-tests.yml"
      - "dev/docker-compose.yml"
      - "verification/curator-service/**"
      - "data-serving/data-service/**"
      - "data-serving/samples/**"
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        browser: ["chrome"]
    name: Cypress tests on ${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v3
      - name: Build stack
        run: docker-compose -f dev/docker-compose.yml -f dev/docker-compose.ci.yml up --build -d -V
      - uses: cypress-io/github-action@v4
        with:
          working-directory: verification/curator-service/ui
          browser: ${{ matrix.browser }}
          record: false
          wait-on: "http://localhost:3002"
          wait-on-timeout: 300
          install-command: sh ./install_in_ci.sh
        env:
          CI: true
          CYPRESS_RECORD_KEY: 1447b996-f025-495f-82d8-ca0b421ffd02
          MONGO_DB_NAME: "covid19"
      # Screenshots are only available on failures.
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: verification/curator-service/ui/cypress/screenshots
      # Videos are always available.
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: verification/curator-service/ui/cypress/videos/components
